### ISSUE TITLE
Inference Error

### ISSUE THREAD

**Issue by Elfilali-Taoufiq** [rstrudel/segmenter#10]
hello, and thanksn for this great work,

I am trying to do inference from the pretrained model, i chose the first model :
**Seg-T-Mask/16 | 38.1 / 38.8 | 7M | 512x512**

then, i want to test for some images with **512*512** resolution, but i got this error 

_RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same_

Thanks

**Comment by woctezuma** [comment]
Ditto. https://github.com/rstrudel/segmenter/issues/11#issuecomment-876396362

**Comment by rstrudel** [comment]
Hi @Elfilali-Taoufiq ,
I pushed a fix, cf #11 . It should be good now.
