### ISSUE TITLE
README: a wrong link 

### ISSUE THREAD

**Issue by woctezuma** [rstrudel/segmenter#12]
The link for the `config` of `Seg-B†/16` in https://github.com/rstrudel/segmenter#model-zoo is wrong

![Illustration](https://i.imgur.com/3NKb0Hi.png)

It should be:

```
https://www.rocq.inria.fr/cluster-willow/rstrudel/segmenter/checkpoints/seg_base_deit_linear/variant.yml
```

**Comment by rstrudel** [comment]
Thanks for catching it and opening an issue! I changed it.
