### ISSUE TITLE
How to train with multi gpu

### ISSUE THREAD

**Issue by BruceYu-Bit** [rstrudel/segmenter#13]
I wonder how to train with multi-gpu

**Comment by chenyangh** [comment]
On a single machine, I simply used `model = torch.nn.DataParallel(model)`, and it works. But this doesn't scale very well.

**Comment by BruceYu-Bit** [comment]
Thanks!
Now i met a new question, i wonder a pretain model with smaller patch size,like 4 or 8. Can u provide?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rstrudel/segmenter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rstrudel/segmenter] How to train with multi gpu (#13)





 
On a single machine, I simply used model = torch.nn.DataParallel(model), and it works. But this doesn't scale very well.

**Comment by rstrudel** [comment]
About 8x8 patches please see #3 . The multi GPU training should work out of the box with slurm but maybe you have another usecase which does not work as is. I am closing this issue but feel free to reopen if you still meet issues with training.
