### ISSUE TITLE
waiting for the code.

### ISSUE THREAD

**Issue by chenjun2hao** [rstrudel/segmenter#2]

**Comment by ShihuaHuang95** [comment]
Waiting

**Comment by hgmlu** [comment]
Looking forward to your code!!!

**Comment by woctezuma** [comment]
I think it is up. https://github.com/rstrudel/segmenter/commit/cef08081980c2d2c90c6779a2fa2d76fdf1f7422

**Comment by rstrudel** [comment]
Yes indeed, we released the code along with checkpoints! I am thus closing this issue for now.
We released improved checkpoints and will update the results in the paper later on.
