### ISSUE TITLE
`start_epoch` in Seg-L-Mask/16 config

### ISSUE THREAD

**Issue by hsfzxjy** [rstrudel/segmenter#24]
I've spotted `start_epoch = 43` in https://www.rocq.inria.fr/cluster-willow/rstrudel/segmenter/checkpoints/ade20k/seg_large_mask_640/variant.yml . Is it a mistake?

**Comment by rstrudel** [comment]
Hi @hsfzxjy , it is not a mistake. It just means we resumed training at some point, in this case epoch 43 and the config file has been overwritten.
