### ISSUE TITLE
Mutli-GPUs training

### ISSUE THREAD

**Issue by qiulesun** [rstrudel/segmenter#29]
This is a good paper and very interested idea! There is a training cmd using a single gpu in readme. For multi-gpus training, could you provide the corresponding cmd ?

**Comment by rstrudel** [comment]
Hi @qiulesun ,
Please check https://github.com/rstrudel/segmenter/issues/22#issuecomment-918863351 , I provide here a slurm batch script to do multi-gpu training.

**Comment by qiulesun** [comment]
The mIoU value of Seg-L-Mask/16 on ADE20K using resolution of **512x512** is not listed in readme (only contain that trained using resolution **640x640**). In terms of this evaluation, do you consider providing such value?

**Comment by rstrudel** [comment]
Sure, on ADE20K for a resolution of 512x512, the mIoU for single-scale/multi-scale is 51.3 / 53.2 .

**Comment by rstrudel** [comment]
I am closing this issue, feel frre to reopen it if you have more questions.
