### ISSUE TITLE
Ask about the "Seg-B/8"

### ISSUE THREAD

**Issue by PkuRainBow** [rstrudel/segmenter#3]
Great work on semantic segmentation!

I find that the resolution is important for the final performance, e.g., Seg-B/8.

However, I could not find that ImageNet pre-trained checkpoints with patch-size 8 from the lib timm.

It would be great if you could help to address my concern!

**Comment by rstrudel** [comment]
Thanks for your interest in our work !
Now that the code is released, I should be able to release Seg-B/8 around next week along with the ViT-B/8 checkpoint converted from jax to torch, I will keep you posted.

**Comment by PavelGrigorev** [comment]
Seg-B/8 would be great!

**Comment by SouthFlame** [comment]
I am also looking forward to the pre-trained model for **vit_base_patch8_384** :) 
I think we can train the model with the pre-trained weights for the below line.
https://github.com/rstrudel/segmenter/blob/0d5fb33ac2c0ea6e6728d4783a4337485dbd6900/segm/model/factory.py#L68

**Comment by BruceYu-Bit** [comment]
how about other kind of patch,like patch size 4,when can you release them

**Comment by woctezuma** [comment]
> 
> 
> how about other kind of patch,like patch size 4,when can you release them

There is no available ViT model as far as I know.

> We provide models pre-trained on ImageNet-21k for the following architectures: ViT-B/16, ViT-B/32, ViT-L/16 and ViT-L/32. We provide the same models pre-trained on ImageNet-21k and fine-tuned on ImageNet.

https://github.com/google-research/vision_transformer#available-vit-models

> We release models with a Vision Transformer backbone initialized from the improved ViT models.

https://github.com/rstrudel/segmenter#model-zoo

**Comment by BruceYu-Bit** [comment]
But i see the patch size 8 in the code,can u release them? @rstrudel

**Comment by rstrudel** [comment]
Hi,
Sorry for the delay. We had quite some work both to update the checkpoints and the paper. I just released Seg-B/8 checkpoints finetuned from the ViT-B/8 backbone from Steiner et al.

**Comment by rstrudel** [comment]
@BruceYu-Bit as mentionned by @woctezuma , there is no ViT models with 4x4 patches. The smaller the patch, the longer the sequence passed to the transformer. As far as I know, with the vanilla transformer blocks things are just too costly to train on 4x4 patches. Maybe other cheaper form of attentions or MLP-Mixer like networks would be better suited to train models on such small patch size.

**Comment by vobecant** [comment]
Hi @rstrudel,
> I just released Seg-B/8 checkpoints finetuned from the ViT-B/8 backbone from Steiner et al.

Do you think that you can please share the weights of the ViT-B/8 with us?
Thank you very much in advance.
