### ISSUE TITLE
train on custom dataset 

### ISSUE THREAD

**Issue by george-kalitsios** [rstrudel/segmenter#36]
hello, I would like to ask if I can modify the existing code to train on my dataset because in a previous issue I read that this is not possible yet. If it's possible Any hints about modifications needed ?

**Comment by davodogster** [comment]
@rstrudel  I'm also interested in this! Cheers

**Comment by Harsh-Gill** [comment]
I am currently working on such a task, i think what he meant by not possible is that the code won't officially support it. Otherwise depending on what your dataset is, it should be possible to train on a custom set.

**Comment by rstrudel** [comment]
Hello,
Thanks for your interest! Indeed the code won't officially support training on custom dataset but it is definitely doable. We have been working on porting Segmenter to mmsegmentation with a PR: https://github.com/open-mmlab/mmsegmentation/pull/955 which is ready to be merged. It is not merged yet but is fully working, you can use [the associated branch](https://github.com/rstrudel/mmsegmentation/tree/dev_mmseg) in the meantime  and follow [their tutorial](https://mmsegmentation.readthedocs.io/en/latest/tutorials/customize_datasets.html) for custom datasets. It's probably one of the simplest way to do it now, I hope this helps.
