### ISSUE TITLE
replicate cityscapes performance

### ISSUE THREAD

**Issue by ekellbuch** [rstrudel/segmenter#41]
Hi, 

Thanks for making the code open source. I was wondering  if you could share the config file you used to train a seg-l/16 model with a vit-l/16 backbone to achieve 80.7% for the cityscapes dataset (second to last row in table 8). When I tried using the same configs as https://www.rocq.inria.fr/cluster-willow/rstrudel/segmenter/checkpoints/cityscapes/seg_large_mask/variant.yml but replacing the decoder the performance  I got was around 75%. Thanks.

**Comment by rstrudel** [comment]
Hi @ekellbuch ,
We released Seg-L/16 checkpoint at the following directory:
https://www.rocq.inria.fr/cluster-willow/rstrudel/segmenter/checkpoints/cityscapes/seg_large_linear/

I hope this can help you reproduce it :)
Robin

**Comment by rstrudel** [comment]
I am closing the issue as it is stale.
