### ISSUE TITLE
where can download the 'vit_base_patch8_384.pth'

### ISSUE THREAD

**Issue by LinB203** [rstrudel/segmenter#43]
thank you for your excellent work, I want to know where can download the 'vit_base_patch8_384.pth', thanks again!

**Comment by Yingyue-L** [comment]
Are you solve the problem?

**Comment by LinB203** [comment]
> Are you solve the problem?

no.

**Comment by Yingyue-L** [comment]
I find in the paper says that the 'vit_base_patch8_384' model just means the vit_base_patch8_224 model.

**Comment by LinB203** [comment]
> I find in the paper says that the 'vit_base_patch8_384' model just means the vit_base_patch8_224 model.

Thanks for your reply, I am doing anothor project, which isn't associated with this repo. B.t.w, if so, that doesn't make sense.
