### ISSUE TITLE
ValueError: DATASET is not defined in the os variables, it is required for data loading.

### ISSUE THREAD

**Issue by zhubingerdai** [rstrudel/segmenter#45]
hi，Why is this error reported during training? Have DATASET folder.ValueError: DATASET is not defined in the os variables, it is required for data loading.

**Comment by rgpinel** [comment]
Hi @zhubingerdai,

It looks like you are missing the `$DATASET` OS variable.

As you can read on the installation section of the `README.md` of this repository, you need to define the OS environment variable pointing to the directory where you store the datasets. 

You could do that by adding the following line in your `.bashrc` file with the corresponding directory:

```
export DATASET=/path/to/dataset/dir
```

**Comment by zhubingerdai** [comment]
thank you!
