### ISSUE TITLE
Why can't Seg-L-Mask/16 be implemented? There will be an error that the weights cannot be loaded

### ISSUE THREAD

**Issue by mazhihao1204** [rstrudel/segmenter#48]
Why can't Seg-L-Mask/16 be implemented? There will be an error that the weights cannot be loaded

**Comment by rstrudel** [comment]
Maybe a GPU memory error?
All checkpoints are also available on [mmsegmentation](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/segmenter) and have been tested there.
