### ISSUE TITLE
Missing mmsegmentation and mmcv in requirements

### ISSUE THREAD

**Issue by theevann** [rstrudel/segmenter#5]
Just so you know, if you wish to update it :)

**Comment by theevann** [comment]
Never mind, I see from your Readme that you probably purposely didn't put it.

**Comment by rstrudel** [comment]
Hi @theevann ,

Thanks for your comment. Yes it's not so obvious as mmcv comes shipped with pytorch and cuda, which is hardware dependent.
I chose to suggest to install torch first and let the user pick something compatible with its hardware before installing mmcv and mmsegmentation.

Robin

**Comment by rstrudel** [comment]
@theevann I added mmcv and mmsegmentation in the requirements, seems to be working without problems and simplifies the setup, thanks for the suggestion !
