### ISSUE TITLE
Infer, Colab

### ISSUE THREAD

**Issue by muhammad-tayyab** [rstrudel/segmenter#6]
Can you please provide single image inference or colab

**Comment by rstrudel** [comment]
Hi @muhammad-tayyab,
This sounds like a good idea, thanks for the suggestion. I just committed a script to do so and [updated the readme](https://github.com/rstrudel/segmenter#inference). Please check it out, I will let this issue open if you have problems and close it otherwise.
Robin

**Comment by muhammad-tayyab** [comment]
@rstrudel Thanks, appreciate your quick action
