### ISSUE TITLE
RuntimeErrorNCCL error

### ISSUE THREAD

**Issue by sym330** [rstrudel/segmenter#60]
The first time I was able to run the program, the second time I had this problem
Thank you for your help and look forward to your reply.

RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:825, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.

**Comment by rstrudel** [comment]
Hi, this does not seem related to the repository. If the problem persists please check pytorch repository for similar issues.
