### ISSUE TITLE
Training on different datasets

### ISSUE THREAD

**Issue by AxelInsa** [rstrudel/segmenter#61]
Hi! I recently discovered this GitHub repository. Great job! I managed to train it on the ADE20K dataset for testing, but I'm having a hard time using my own dataset (I have images and masks). Any help would be appreciated. Thanks again for your help! :smiley:

**Comment by rstrudel** [comment]
Hi,
Thank you for your interest! As mentioned in previous issues, this repo is not meant to support custom datasets. I cannot help personally each person trying that unfortunately. However the good news is Segmenter is available on [mmsegmentation](https://github.com/open-mmlab/mmsegmentation/tree/main/configs/segmenter), and they have instructions to train on your [custom dataset](https://mmsegmentation.readthedocs.io/en/latest/advanced_guides/add_datasets.html). 
Also, to test your scripts, as a starting point, try Segmenter-Tiny with a linear head which is the simplest/fastest setup.
I strongly encourage you to check this and hope this helps!

**Comment by sym330** [comment]
I tried to use a linear head, but the metrics remained the same

**Comment by AxelInsa** [comment]
Thank  you for your response. I checked mmsegmentation and was able (after a bit of struggling) to make it work. Thanks again :)

Edit: I'm struggling with config, it does not work yet

**Comment by lianzheng-research** [comment]
> Thank you for your response. I checked mmsegmentation and was able (after a bit of struggling) to make it work. Thanks again :)
> 
> Edit: I'm struggling with config, it does not work yet

Hi! Have you solved the problem? Could you please share the configs? Thank you!
