### ISSUE TITLE
losses keep going down but my mIOU stays the same. 

### ISSUE THREAD

**Issue by sym330** [rstrudel/segmenter#62]
I put my own data set into the ade20k folder and used "python -m segm.train --log-dir seg_tiny_mask --dataset ade20k \
  --backbone vit_tiny_patch16_384 --decoder mask_transformer" for training.  I set  data.ade20k.py as follow , to detection oil.

```
class ADE20KSegmentation(BaseMMSeg):
    def __init__(self, image_size, crop_size, split, **kwargs):
        super().__init__(
            image_size,
            crop_size,
            split,
            ADE20K_CONFIG_PATH,
            **kwargs,
        )
        self.names, self.colors = utils.dataset_cat_description(ADE20K_CATS_PATH)
        self.n_cls = 2
        self.ignore_label = 255
        self.reduce_zero_label =False
```
 How is the.yml file set up in data?My data set has only one class of objects and backgrounds.
I set it as follows:
- color:
  - 127
  - 0
  - 0
  id: 0
  isthing: 0
  name: oil
- color:
  - 0
  - 0
  - 0
  id: 1
  isthing: 0
  name: background
But my losses keep going down but my mIOU stays the same. This question has been bothering me for a long time. Looking forward to your reply.

**Comment by rstrudel** [comment]
Hi, thanks for your interest! Please check #61 as this is a similar request.

**Comment by sym330** [comment]
I soved it， thank you
