### ISSUE TITLE
The meaning of  num_extra_tokens = 1 + self.image_encoder.distilled

### ISSUE THREAD

**Issue by Y-NY** [rstrudel/segmenter#63]
in class sgementer, forward function:
num_extra_tokens = 1 + self.image_encoder.distilled
x = x[:, num_extra_tokens:]

What do these two lines of code mean？How does 'distilled' define by myself?

**Comment by rstrudel** [comment]
In DeiT's case, the vision backbone have two extra tokens, one CLS token, used to perform classification, and one distillation token, used to match a teacher's output. You can see it in Figure 2 of [DeiT](https://arxiv.org/abs/2012.12877).
The line `x[:, num_extra_token:]` means we're getting all of the patch tokens, CLS and distillation tokens excluded.
