### ISSUE TITLE
mmseg not found !!

### ISSUE THREAD

**Issue by Elfilali-Taoufiq** [rstrudel/segmenter#8]
hello and thanks for this great work,

i am trynig to test your code using Inference, but y get this error:
ModuleNotFoundError: No module named 'mmseg'

then i tried to install mmseg  using pip, but it's not working : 
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Best,

**Comment by rstrudel** [comment]
Hi @Elfilali-Taoufiq ,
I just tried again to install the library in a new environment and it seems to be working on my side.
Did you do `pip install .` at the root of the cloned repository ?
When installing, you should see a message similar to the one below at the end:
```python
Building wheels for collected packages: segm
  Building wheel for segm (setup.py) ... done
  Created wheel for segm: filename=segm-0.0.1-py3-none-any.whl size=1083 sha256=fa67427a090ab4ea7ade7af23533953b3beedbfede14b4942d4a90dd0c9e22d0
  Stored in directory: /tmp/pip-ephem-wheel-cache-tt_ylejw/wheels/82/12/3a/3449e57cb2aeeb756ab684f7c9bf325a6c0bb8f9c5139d7451
Successfully built segm
Installing collected packages: mmsegmentation, mmcv, segm
  Attempting uninstall: segm
    Found existing installation: segm 0.0.1
    Uninstalling segm-0.0.1:
      Successfully uninstalled segm-0.0.1
Successfully installed mmcv-1.3.8 mmsegmentation-0.14.1 segm-0.0.1
```

**Comment by Elfilali-Taoufiq** [comment]
> Hi @Elfilali-Taoufiq ,
> I just tried again to install the library in a new environment and it seems to be working on my side.
> Did you do `pip install .` at the root of the cloned repository ?
> When installing, you should see a message similar to the one below at the end:
> 
> ```python
> Building wheels for collected packages: segm
>   Building wheel for segm (setup.py) ... done
>   Created wheel for segm: filename=segm-0.0.1-py3-none-any.whl size=1083 sha256=fa67427a090ab4ea7ade7af23533953b3beedbfede14b4942d4a90dd0c9e22d0
>   Stored in directory: /tmp/pip-ephem-wheel-cache-tt_ylejw/wheels/82/12/3a/3449e57cb2aeeb756ab684f7c9bf325a6c0bb8f9c5139d7451
> Successfully built segm
> Installing collected packages: mmsegmentation, mmcv, segm
>   Attempting uninstall: segm
>     Found existing installation: segm 0.0.1
>     Uninstalling segm-0.0.1:
>       Successfully uninstalled segm-0.0.1
> Successfully installed mmcv-1.3.8 mmsegmentation-0.14.1 segm-0.0.1
> ```

**Comment by Elfilali-Taoufiq** [comment]
yes, that's right, thank youu @rstrudel

**Comment by woctezuma** [comment]
> then i tried to install mmseg using pip, but it's not working

I think it was a confusion between `mmseg` and `mmsegmentation`, similar to https://github.com/facebookresearch/xcit/issues/14
