### ISSUE TITLE
Pretrained weights for Pascal Context

### ISSUE THREAD

**Issue by RuskinManku** [rstrudel/segmenter#9]
Hi,
Great work and thanks for providing code online. In the model zoo you have provided weights for various versions trained on ADE20K, however in the paper you have also mentioned about training on Pascal Context. Is it possible to provide weights for the same?

**Comment by rstrudel** [comment]
Hi @RuskinManku ,
We updated the model zoo with Pascal Context. As said in previous issues, we plan to update the arXiv paper to report the improved numbers of the repository.
Robin
